apiVersion: v1
kind: Service
metadata:
  name: aks-demo-app
  namespace: saanvikit
spec:
  type: LoadBalancer
  selector:
    app: aks-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
